BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Visitante" (
	"VisitanteId"	INTEGER UNIQUE,
	"Nombre"	INTEGER NOT NULL,
	"Apellido"	INTEGER NOT NULL,
	"Edad"	INTEGER NOT NULL,
	PRIMARY KEY("VisitanteId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ControlPatio" (
	"ReclusaId"	INTEGER,
	"HoraEntrada"	TEXT NOT NULL,
	"HoraSalida"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Visitas" (
	"VisitaId"	INTEGER UNIQUE,
	"Fecha"	TEXT NOT NULL,
	"Hora"	TEXT NOT NULL,
	"ReclusaId"	INTEGER NOT NULL,
	"VisitanteId"	INTEGER NOT NULL,
	PRIMARY KEY("VisitaId" AUTOINCREMENT),
	FOREIGN KEY("ReclusaId") REFERENCES "Reclusas"("ReclusasId")
);
CREATE TABLE IF NOT EXISTS "Reclusas" (
	"ReclusasId"	INTEGER UNIQUE,
	"Nombre"	TEXT NOT NULL,
	"Apellido"	TEXT NOT NULL,
	"Edad"	NUMERIC NOT NULL,
	"Grado"	INTEGER NOT NULL,
	"CondenaRestante"	INTEGER NOT NULL,
	"VisitaId"	INTEGER NOT NULL,
	FOREIGN KEY("VisitaId") REFERENCES "Visitas"("VisitaId"),
	PRIMARY KEY("ReclusasId" AUTOINCREMENT)
);
COMMIT;
